// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation.Infrastructure.Persistence;

#nullable disable

namespace Reservation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904100621_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservation.Domain.Reservations.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("PartySize");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Reservation_Status");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("Reservation.Domain.Reservations.Reservation", b =>
                {
                    b.OwnsOne("Reservation.Domain.Reservations.Guest", "Guest", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("GuestName");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");

                            b1.OwnsOne("Reservation.Domain.Reservations.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("GuestReservationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .IsUnicode(false)
                                        .HasColumnType("varchar(20)")
                                        .HasColumnName("GuestPhone");

                                    b2.HasKey("GuestReservationId");

                                    b2.ToTable("Reservations");

                                    b2.WithOwner()
                                        .HasForeignKey("GuestReservationId");
                                });

                            b1.Navigation("PhoneNumber")
                                .IsRequired();
                        });

                    b.OwnsMany("Reservation.Domain.Reservations.TableNo", "Tables", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("TableNo");

                            b1.HasKey("ReservationId", "Value");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_Reservation_TableNo");

                            b1.ToTable("ReservationTables", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.OwnsOne("Reservation.Domain.Reservations.TimeSlot", "Slot", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Duration")
                                .HasColumnType("int")
                                .HasColumnName("Duration");

                            b1.Property<DateTimeOffset>("StartAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("StartAt");

                            b1.HasKey("ReservationId");

                            b1.HasIndex("StartAt")
                                .HasDatabaseName("IX_Reservation_StartAt");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Guest")
                        .IsRequired();

                    b.Navigation("Slot")
                        .IsRequired();

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
