using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Reservation.Domain.Reservations;
using ReservationAggregate = Reservation.Domain.Reservations.Reservation;

namespace Reservation.Infrastructure.Persistence.Configurations {
    public sealed class ReservationConfiguration : IEntityTypeConfiguration<ReservationAggregate> {
        public void Configure(EntityTypeBuilder<ReservationAggregate> builder) {
            //什麼時候用OwnsOne/OwnsMany ?什麼時候直接用Prperty?
            //如果該欄位是簡單資料型態,ex:int,string,gui,那就直接用".Property"
            //否則就是用Owns去設定

            builder.ToTable("Reservations");
            builder.HasKey(r => r.id);
            builder.Property(r => r.Id)
                .HasColumnName("Id")
                .HasConversion(id => id.Value, v => ReservationId.From(v))    //<--2 func:convertTo & convertFrom
                .ValueGeneratedNever();   //Id 由"Reservation.Place()"產生,非DB的gui欄位
            //"Guest" column has nested VO--PhoneNumber
            builder.OwnsOne(r => r.Guest, g => {
                g.Property(x => x.Name)
                 .HasColumnName("GuestName")
                 .HasMaxLength(50)
                 .IsRequired();
                g.OwnsOne(x => x.PhoneNumber, p => {
                    p.Property(v => v.Number)
                     .HasColumnName("GuestPhone")
                     .HasMaxLength(20)
                     .IsUnicode(false)        //<--numeric data.
                     .IsRequired();

                });
                g.Navigation(x => x.PhoneNumber).IsRequired();
            });
            //TimeSlot column;StartAt is required,
            //but "EndAt" is generated by calculation, no need "Required"
            //這包「Slot」物件,有三個欄位:StartAt & EndAt& Duration,都是同一層,所以沒有「Owns....」
            //不像Guest裡面又有Name又有Phonenumber <--所以有「OwnsOne」
            builder.OwnsOne(r => r.Slot, s => {
                s.Property(x => x.StartAt)
                 .HasColumnName("StartAt")
                 .IsRequired();
                s.Property(x => x.Duration)
                 .HasColumnName("Duration")
                 .HasConversion(t => (int)t.Minutes, f => TimeSpan.FromMinutes(f))
                 .IsRequired();
                s.HasIndex(x => x.StartAt).HasDatabaseName("IX_Reservation_StartAt");
            });
            builder.Navigation(x => x.Slot).IsRequired();
            //--PartySize---
            builder.Property(r => r.Size)
                .HasColumnName("PartySize")
                .HasConversion(t => t.Value, f => PartySize.Of(f))
                .IsRequired();
            //--Status---
            builder.Property(r => r.Status)
                .HasColumnName("Status")
                .HasConversion<string>()
                .HasMaxLength(20)
                .IsUnicode(false)   //<--純英文,非unicode文字,如果是中文就要true了
                .IsRequired();


        }
    }
}
