using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Reservation.Domain.Reservations;
using ReservationAggregate = Reservation.Domain.Reservations.Reservation;

namespace Reservation.Infrastructure.Persistence.Configurations {
    public sealed class ReservationConfiguration : IEntityTypeConfiguration<ReservationAggregate> {
        public void Configure(EntityTypeBuilder<ReservationAggregate> builder) {
            //什麼時候用OwnsOne/OwnsMany ?什麼時候直接用Prperty?
            //如果該欄位是簡單資料型態,ex:int,string,gui,那就直接用".Property"
            //否則就是用Owns去設定

            builder.ToTable("Reservations");
            builder.HasKey(r => r.id);
            builder.Property(r => r.Id)
                .HasColumnName("Id")
                .HasConversion(id => id.Value, v => ReservationId.From(v))    //<--2 func:convertTo & convertFrom
                .ValueGeneratedNever();   //Id 由"Reservation.Place()"產生,非DB的gui欄位
            //"Guest" column has nested VO--PhoneNumber
            builder.OwnsOne(r => r.Guest, g => {
                g.Property(x => x.Name)
                 .HasColumnName("GuestName")
                 .HasMaxLength(50)
                 .IsRequired();
                g.OwnsOne(x => x.PhoneNumber, p => {
                    p.Property(v => v.Number)
                     .HasColumnName("GuestPhone")
                     .HasMaxLength(20)
                     .IsUnicode(false)        //<--numeric data.
                     .IsRequired();

                });
                g.Navigation(x => x.PhoneNumber).IsRequired();
            });
            builder.Navigation(r => r.Guest).IsRequired();

            //TimeSlot column;StartAt is required,
            //but "EndAt" is generated by calculation, no need "Required"
            //這包「Slot」物件,有三個欄位:StartAt & EndAt& Duration,都是同一層,所以沒有「Owns....」
            //不像Guest裡面又有Name又有Phonenumber <--所以有「OwnsOne」
            builder.OwnsOne(r => r.Slot, s => {
                s.Property(x => x.StartAt)
                 .HasColumnName("StartAt")
                 .IsRequired();
                s.Property(x => x.Duration)
                 .HasColumnName("Duration")
                 .HasConversion(t => (int)t.Minutes, f => TimeSpan.FromMinutes(f))
                 .IsRequired();
                s.HasIndex(x => x.StartAt).HasDatabaseName("IX_Reservation_StartAt");
            });
            builder.Navigation(x => x.Slot).IsRequired();
            //--PartySize---
            builder.Property(r => r.Size)
                .HasColumnName("PartySize")
                .HasConversion(t => t.Value, f => PartySize.Of(f))
                .IsRequired();
            //--Status---
            builder.Property(r => r.Status)
                .HasColumnName("Status")
                .HasConversion<string>()
                .HasMaxLength(20)
                .IsUnicode(false)   //<--純英文,非unicode文字,如果是中文就要true了
                .IsRequired();
            builder.HasIndex(r => r.Status).HasDatabaseName("IX_Reservation_Status");

            //精彩的來了....一單多桌,可以想做order 1---* prod Items關係
            builder.OwnsMany(r => r.Tables, t => {
                t.ToTable("ReservationTables");
                t.WithOwner().HasForeignKey("ReservationId");
                t.Property(x => x.Value)
                 .HasColumnName("TableNo")
                 .HasMaxLength(10)
                 .IsUnicode(false)
                 .IsRequired();
                //multi-PK,make sure "ReservationId+TabeNo" is unique ,even we did "Distinct()" while allocating table.
                //原文是「 t.HasKey("ReservationId", "Value");」,為了好了解,所以加上nameof
                t.HasKey("ReservationId", nameof(TableNo.Value)); 
                t.HasIndex(t => t.Value).HasDatabaseName("IX_Reservation_TableNo");
            });

            //Tables 是唯讀屬性，EF 需直接寫入背後的 _tables 欄位。
            /*
            builder.OwnsMany(r => r.Tables, t => { ... });   // configures the TableNo type: table, columns, key
            builder.Navigation(r => r.Tables)                 // configures the Tables property on Reservation:
             .UsePropertyAccessMode(PropertyAccessMode.Field);   // how EF reads/writes it            
            */

            builder.Navigation(r => r.Tables)
                .UsePropertyAccessMode(PropertyAccessMode.Field);
            //↑回去Domain看一下那"Reservation.Domain.Reservations.Reservation"
            //那裡有關_tables定義時寫的說明,與此呼應


            builder.Ignore(r => r.DomainEvents);

        }
    }
}
