using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Reservation.Domain.Reservations;
using ReservationAggregate = Reservation.Domain.Reservations.Reservation;

namespace Reservation.Infrastructure.Persistence.Configurations {
    public sealed class ReservationConfiguration : IEntityTypeConfiguration<ReservationAggregate> {
        public void Configure(EntityTypeBuilder<ReservationAggregate> builder) {
            //什麼時候用OwnsOne/OwnsMany ?什麼時候直接用Prperty?
            //如果該欄位是簡單資料型態,ex:int,string,gui,那就直接用".Property"
            //否則就是用Owns去設定

            builder.ToTable("Reservations");
            builder.HasKey(r => r.Id);
            builder.Property(r => r.Id)
                .HasColumnName("Id")
                .HasConversion(id => id.Value, v => ReservationId.From(v))    //<--2 func:convertTo & convertFrom
                .ValueGeneratedNever();   //Id 由"Reservation.Place()"產生,非DB的gui欄位
            //"Guest" column has nested VO--PhoneNumber
            builder.OwnsOne(r => r.Guest, g => {
                g.Property(x => x.Name)
                 .HasColumnName("GuestName")
                 .HasMaxLength(50)
                 .IsRequired();
                g.OwnsOne(x => x.PhoneNumber, p => {
                    p.Property(v => v.Number)
                     .HasColumnName("GuestPhone")
                     .HasMaxLength(20)
                     .IsUnicode(false)        //<--numeric data.
                     .IsRequired();

                });
                g.Navigation(x => x.PhoneNumber).IsRequired();
            });
            builder.Navigation(r => r.Guest).IsRequired();

            //TimeSlot column;StartAt is required,
            //but "EndAt" is generated by calculation, no need "Required"
            //這包「Slot」物件,有三個欄位:StartAt & EndAt& Duration,都是同一層,所以沒有「Owns....」
            //不像Guest裡面又有Name又有Phonenumber <--所以有「OwnsOne」
            builder.OwnsOne(r => r.Slot, s => {
                s.Property(x => x.StartAt)
                 .HasColumnName("StartAt")
                 .IsRequired();
                s.Property(x => x.Duration)
                 .HasColumnName("Duration")
                 //.HasConversion(t => (int)t.Minutes, f => TimeSpan.FromMinutes(f))
                 //小心,不是(int)t.Minutes,but is TotalMinutes!!
                 .HasConversion(t => (int)t.TotalMinutes, f => TimeSpan.FromMinutes(f))
                 .IsRequired();
                s.HasIndex(x => x.StartAt).HasDatabaseName("IX_Reservation_StartAt");
            });
            builder.Navigation(x => x.Slot).IsRequired();
            //--PartySize---
            builder.Property(r => r.Size)
                .HasColumnName("PartySize")
                .HasConversion(t => t.Value, f => PartySize.Of(f))
                .IsRequired();
            //--Status---
            builder.Property(r => r.Status)
                .HasColumnName("Status")
                .HasConversion<string>()
                .HasMaxLength(20)
                .IsUnicode(false)   //<--純英文,非unicode文字,如果是中文就要true了
                .IsRequired();
            builder.HasIndex(r => r.Status).HasDatabaseName("IX_Reservation_Status");

            //精彩的來了....一單多桌,可以想做order 1---* prod Items關係
            builder.OwnsMany(r => r.Tables, t => {
                t.ToTable("ReservationTables");
                t.WithOwner().HasForeignKey("ReservationId");
                t.Property(x => x.Value)
                 .HasColumnName("TableNo")
                 .HasMaxLength(10)
                 .IsUnicode(false)
                 .IsRequired();
                //multi-PK,make sure "ReservationId+TabeNo" is unique ,even we did "Distinct()" while allocating table.
                //原文是「 t.HasKey("ReservationId", "Value");」,為了好了解,所以加上nameof
                t.HasKey("ReservationId", nameof(TableNo.Value)); 
                t.HasIndex(x => x.Value).HasDatabaseName("IX_Reservation_TableNo");
            });

            //Tables 是唯讀屬性，EF 需直接寫入背後的 _tables 欄位。
            /*
            builder.OwnsMany(r => r.Tables, t => { ... });   // configures the TableNo type: table, columns, key
            builder.Navigation(r => r.Tables)                 // configures the Tables property on Reservation:
             .UsePropertyAccessMode(PropertyAccessMode.Field);   // how EF reads/writes it            
            */

            builder.Navigation(r => r.Tables)
                .UsePropertyAccessMode(PropertyAccessMode.Field);
            //↑回去Domain看一下那"Reservation.Domain.Reservations.Reservation"
            //那裡有關_tables定義時寫的說明,與此呼應

            /*
這兩行設定的是**兩件不同的事**,只是因為在檔案裡相鄰,很容易誤以為重複。

```csharp
builder.OwnsMany(r => r.Tables, t => { ... });   // 設定 TableNo 這個型別:資料表、欄位、主鍵
builder.Navigation(r => r.Tables)                 // 設定 Reservation 上的 Tables 屬性:
       .UsePropertyAccessMode(PropertyAccessMode.Field);   // EF 要怎麼讀寫它
```

`OwnsMany`
            回答的是「**存什麼、存在哪**」。
            `Navigation` 回答的是「**EF 要怎麼碰到這個集合**」。對應設得再完美,materialization 還是可能失敗。

## 具體會怎麼壞

你的聚合根幾乎確定長這樣:

```csharp
private readonly List<TableNo> _tables = new();
public IReadOnlyList<TableNo> Tables => _tables;
```

想一下 EF 載入一筆 reservation 時要做什麼。它查出那幾筆 row,建出每個 `TableNo`,然後需要**把它們塞進集合裡**。
            透過屬性拿到的是 `IReadOnlyList<TableNo>` —— 沒有 `Add`。根本進不去。EF 必須繞過屬性,直接摸到底下那個 `List<TableNo>` 欄位。

存檔時同理:變更追蹤需要的是那個**實際的 list 實例**,才能拿去跟快照比對。

## 為什麼有時候不寫也會動

EF 本來就會依慣例去找 backing field。對於屬性 `Tables`,它會找 `_tables`、`_Tables`、`m_tables`、`m_Tables`。如果你的欄位剛好叫 `_tables`,慣例找得到,那行確實是多餘的。

但名字一飄掉就失效:

```csharp
private readonly List<TableNo> _reservationTables = new();   // 慣例找不到
public IReadOnlyList<TableNo> Tables => _reservationTables;
```

所以明確寫出來,有一部分是在保險 —— 防的是那種**沒有任何編譯器會警告你**的改名。

## 更安靜的那個陷阱

這個值得放進你的課程教材:

```csharp
public IReadOnlyList<TableNo> Tables => _tables.ToList();   // 防禦性複製
```

以你先前在 domain event 上處理防禦性複製的經驗,這個直覺一定會冒出來。但在這裡它是**有害的**。只要 EF 曾經透過屬性讀取,它每次呼叫拿到的都是**一份新的複本**。新增的元素進了一個馬上要被回收的 list。沒有例外、沒有錯誤 —— 桌號就是存不進去。

`AsReadOnly()` 沒那麼糟(wrapper 共用底層的 list),但它每次存取仍然給 EF 一個新物件,這不是變更追蹤想要的。

`PropertyAccessMode.Field` 的意思是 EF **完全不碰**那個屬性,所以上面這些都咬不到你。這才是真正的價值:它讓持久化層對「領域層在 getter 裡做了什麼」免疫。

## 一個有用的副作用

`PropertyAccessMode.Field` 在找不到欄位時,會在 **model building 階段**就失敗 —— 啟動時炸,不是第一次查詢才炸。跟那種靜悄悄降級的慣例設定比起來,fail-fast 光這點就值回那一行。

如果你不想多寫一個獨立的敘述句,也可以直接對欄位做對應:

```csharp
builder.OwnsMany<TableNo>("_tables", t => { ... });
```

這樣 EF 根本不知道那個屬性存在。某種意義上更乾淨,但字串很脆,IDE 導航也變差。以教學用的程式碼來說,明確寫出 `Navigation(...)` 那行讀起來更好 —— 學生可以同時看到兩半,並理解它們回答的是不同的問題。
            
           */
            //2026/09/05,add "Note" column
            builder.Property(r => r.Note)
                 .HasColumnName("Note")
                 .HasConversion<string>()
                 .HasMaxLength(200)
                 .IsUnicode(true);   //<--多語系

            builder.Ignore(r => r.DomainEvents);

        }
    }
}
